image: python:3.9.6

stages:
  - test
  - deploy

unit-test-job:   # This job runs in the test stage.
  only:
    - master
    - merge_requests
  variables:
    COVERAGE_DIR: "coverage-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
  stage: test    # It only starts when the job in the build stage completes successfully.
  before_script:
    - pip install -r requirements.txt
  script:
    - echo "Running unit tests... This will take about 10 seconds."
    - coverage run --source=online_store manage.py test online_store
    - coverage html -d $COVERAGE_DIR
  artifacts:
    name: "coverage-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - $COVERAGE_DIR
    expire_in: 1 week
    when: on_success

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
