"""add field body to card table 

Revision ID: 0f6358009d0c
Revises: e1f1ae928343
Create Date: 2021-12-16 19:35:52.272659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f6358009d0c'
down_revision = 'e1f1ae928343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'body')
    # ### end Alembic commands ###
