"""add column created_at to cards table

Revision ID: a7738195f049
Revises: 8a68587397be
Create Date: 2021-12-16 18:57:41.440630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7738195f049'
down_revision = '8a68587397be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'created_at')
    # ### end Alembic commands ###
