"""add flag unique to Card.name

Revision ID: e1f1ae928343
Revises: a7738195f049
Create Date: 2021-12-16 19:15:43.004017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f1ae928343'
down_revision = 'a7738195f049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'card', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='unique')
    # ### end Alembic commands ###
