version: '3'

services:
  calendar:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONFIG: DevelopmentConfig
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://app:password@pg:5432/calendar
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    depends_on:
      - pg

  calendar-prod:
    build:
      context: .
      dockerfile: ./docker-build/calendar-prod/Dockerfile
    environment:
      CONFIG: ProductionConfig
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://app:password@pg:5432/calendar
    ports:
      - "5080:80"
    depends_on:
      - pg

  pg:
    image: postgres # use latest official postgres version
    environment:
      POSTGRES_DB: calendar
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data/ # persist data even if container shuts down


volumes:
  pg-data: